### ISSUE TITLE
How to make ur3e.usd

### ISSUE THREAD

**Issue by curieuxjy** [DarK404/UR_Isaac-sim#2]
Hello,

I found the `ur3e.usd` file in your repository that combines a UR3E robot and a Robotiq gripper.

I'm working on creating a UR10+Robotiq2F85 USD file and I wanted to refer to your method of making `ur3e.usd`. 

First, I followed the instructions from this document (https://docs.omniverse.nvidia.com/isaacsim/latest/advanced_tutorials/tutorial_advanced_assembling_robots.html#assembling-robots-and-rigid-bodies) to assemble a UR10 and Robotiq 2F85 gripper.

However, I encountered an issue:

![image 6](https://github.com/DarK404/UR_Isaac-sim/assets/40867411/4211a04a-a7f2-4ee0-9a52-3f677b29b534)

When I ran the UR10+Robotiq USD file according to the assembly instructions, its movement was unusual.

Could you please share your method for creating the `ur3e.usd` file? It would be extremely helpful.

Thank you for your time.

**Comment by DarK404** [comment]
I believe the error you're encountering may be due to the improper definition of the joint bodies. Take a look at my USD file to see how I've defined them:
![image](https://github.com/DarK404/UR_Isaac-sim/assets/28174056/bb8c5755-8a1e-4b54-a9a9-72bc35c47f9a)

Additionally, I recommend watching this video tutorial which might help you create your USD file effectively:
[Video Tutorial](https://www.youtube.com/watch?v=pMu3mMG7P4E)

**Comment by curieuxjy** [comment]
thanks a lot for your reply.

I will check that definition and watch the tutorial video too! 😃
